agents:
  SK:
    intra_id: 396
    default_rate_type: EK1
  GS:
    intra_id: 1665
    default_rate_type: PR3

clients:
  NT:
    intra_id: 8
    sheet_prefix: НТР
    report_group: Group_01
    rates:
      EK1: 1200
  VG:
    intra_id: 12
    sheet_prefix: ВГЭР
    report_group: Group_02
    rates:
      EK1: 1300
      PR3: 2500
  BG:
    report_group: Group_03
    intra_id: 30
    sheet_prefix: БЛР
    rates:
      EK1: 1300
      PR3: 2500

rate_description:
  EK1: ЭК1
  EK2: ЭК2
  EK3: ЭК3
  PR3: ПР3

xls:
  Тикет: [task_id, 7]
  Содержание: [name, 50]
  Инициатор: [creator, 20]
  ЧЧ: [hours, 5]
  Ставка: [rate, 6]
  Исполнитель: [agent_name, 20]
  Стоимость: [value, 10]
  Детализация: [exp_details, 50]




