import re
import requests
from unittest import TestCase
from datetime import datetime

import psycopg2
from psycopg2 import sql

from keys import KeyChain

def scan_levels(pg_key):
    url = 'http://www.meteo.nw.ru/weather/lo_levelsd.php'
    response = requests.get(url)
    response.encoding = 'windows-1251'
    html = response.text
    re_html = r"markers_mapm = \[([^\[]+)\]"
    array = re.findall(re_html, html, re.MULTILINE)[0]
    re_array = r"'bubble':'<b>(.+)</b><br>уровень: <i>(.+)</i> см<br /><br /><br />"
    points = re.findall(re_array, array, re.MULTILINE)

    connection = psycopg2.connect(dbname=pg_key["db_name"], user=pg_key["user"],
                           password=pg_key["pwd"], host=pg_key["host"])

    cursor = connection.cursor()

    stamp = datetime.now()
    for point in points:
        query = sql.SQL('insert into {} ({}, {}, {}) values ({}, {}, {})').format(
            sql.Identifier('Levels'),
            sql.Identifier('stamp'),
            sql.Identifier('point'),
            sql.Identifier('level'),
            sql.Literal(stamp),
            sql.Literal(point[0]),
            sql.Literal(int(point[1])),
        )
        cursor.execute(query)
    connection.commit()



class LevelscanTestKeys(TestCase):
    def test_scan_level(self):
        scan_levels(KeyChain.PG_KEY)
        pass

    def test_pure(self):

        # test_str = (
        #     "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
        #     "      <html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
        #     "      <head>\n"
        #     "          <link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\n"
        #     "          <link rel=\"shortcut icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\n"
        #     "          <meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1251\">\n"
        #     "          <meta HTTP-EQUIV=\"Expires\" CONTENT=\"0\">\n"
        #     "          <meta HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\">\n"
        #     "          <meta HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache\">\n"
        #     "          <!--<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=yes\">-->\n"
        #     "          <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\n"
        #     "          <link href=\"/images/css/style.css?t=1.0.1\" media=\"all\" rel=\"stylesheet\" type=\"text/css\"><meta name=\"Keywords\" content=\"карта фактического уровня воды, уровень воды, уровни воды в лениградской области, уровень воды в санкт-петербурге\">\n"
        #     "          <meta name=\"Description\" content=\"\">\n"
        #     "          <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyCEY-3JPOGedhJJd5weNkdQKwEbb32O2gY&sensor=false\" type=\"text/javascript\"></script>\n"
        #     "          <script type=\"text/javascript\" src=\"/jscripts/jquery-1.9.1.js\"></script>\n"
        #     "          <script type=\"text/javascript\" src=\"/jscripts/jquery.mousewheel.js\"></script>\n"
        #     "          <script src=\"https://code.jquery.com/jquery-migrate-1.4.1.min.js\"></script> \n"
        #     "          <title>Карта фактического уровня воды в Финском заливе и реке Неве | Официальный портал Северо-Западного УГМС, прогноз погоды по Санкт-Петербургу на трое суток</title><!-- Yandex.Metrika counter -->\n"
        #     "<script type=\"text/javascript\" >\n"
        #     "    (function (d, w, c) {\n"
        #     "        (w[c] = w[c] || []).push(function() {\n"
        #     "            try {\n"
        #     "                w.yaCounter50309731 = new Ya.Metrika2({\n"
        #     "                    id:50309731,\n"
        #     "                    clickmap:true,\n"
        #     "                    trackLinks:true,\n"
        #     "                    accurateTrackBounce:true,\n"
        #     "                    webvisor:true\n"
        #     "                });\n"
        #     "            } catch(e) { }\n"
        #     "        });\n\n"
        #     "        var n = d.getElementsByTagName(\"script\")[0],\n"
        #     "            s = d.createElement(\"script\"),\n"
        #     "            f = function () { n.parentNode.insertBefore(s, n); };\n"
        #     "        s.type = \"text/javascript\";\n"
        #     "        s.async = true;\n"
        #     "        s.src = \"https://mc.yandex.ru/metrika/tag.js\";\n\n"
        #     "        if (w.opera == \"[object Opera]\") {\n"
        #     "            d.addEventListener(\"DOMContentLoaded\", f, false);\n"
        #     "        } else { f(); }\n"
        #     "    })(document, window, \"yandex_metrika_callbacks2\");\n"
        #     "</script>\n"
        #     "<noscript><div><img src=\"https://mc.yandex.ru/watch/50309731\" style=\"position:absolute; left:-9999px;\" alt=\"\" /></div></noscript>\n"
        #     "<!-- /Yandex.Metrika counter -->\n"
        #     "          </head><body ><script type=\"text/javascript\">\n"
        #     "     $(document).ready(function(){\n\n"
        #     "                $(\"#show_toggle\").click(function(){\n"
        #     "                      $(\"#wfinfo\").slideToggle(\"slow\");\n"
        #     "                      $(\"#wfinfo2\").slideToggle(\"slow\");\n"
        #     "                      if ($(this).text() == \"показать в текстовой форме\")\n"
        #     "                         $(this).text(\"показать в табличной форме\");\n"
        #     "                      else\n"
        #     "                         $(this).text(\"показать в текстовой форме\");\n"
        #     "                      \n"
        #     "                });\n"
        #     "                $(\"#wforecast\").on(\"click\", \"#wfinfo\", function(){\n"
        #     "                      $(\"#wfinfo\").hide(\"slow\");\n"
        #     "                      $(\"#wfinfo2\").show(\"slow\");\n"
        #     "                      if ($(\"#show_toggle\").text() == \"показать в текстовой форме\")\n"
        #     "                         $(\"#show_toggle\").text(\"показать в табличной форме\");\n"
        #     "                      else\n"
        #     "                         $(\"#show_toggle\").text(\"показать в текстовой форме\");\n"
        #     "                });\n"
        #     "                $(\"#wforecast\").on(\"click\", \"#wfinfo2\", function(){\n"
        #     "                      $(\"#wfinfo2\").hide(\"slow\");\n"
        #     "                      $(\"#wfinfo\").show(\"slow\");\n"
        #     "                      if ($(\"#show_toggle\").text() == \"показать в текстовой форме\")\n"
        #     "                         $(\"#show_toggle\").text(\"показать в табличной форме\");\n"
        #     "                      else\n"
        #     "                         $(\"#show_toggle\").text(\"показать в текстовой форме\");\n"
        #     "                });\n"
        #     "                $(\".hmenuun:not(.active)\").hover(function(){\n"
        #     "                                    $(this).css(\"background\", \"url(/images/css/active_menu.jpg) top repeat-x\");\n"
        #     "                                    },\n"
        #     "                                    function(){\n"
        #     "                                      $(this).css(\"background\", \"none\");\n"
        #     "                                    });\n\n"
        #     "                /*if ($(\"#img_div img\").width() > 539) $(\"#img_div img\").width(539);*/\n"
        #     "                flag = 0;\n"
        #     "                $(\"#img_div img\").each(function(){\n"
        #     "                                                  flag = 1;\n"
        #     "                                                  $(this).bind(\"load\", function(){\n"
        #     "                                                        if ($(this).width() > 539) $(this).width(539);\n"
        #     "                                                        if ($(\".page_middle\").height() < 600) $(\".page_middle\").height(600);\n"
        #     "                                                  });\n"
        #     "                });\n"
        #     "                \n"
        #     "                $(\".mmcontent img\").click(function(){\n"
        #     "                   src_img = $(this).attr(\"src\");\n"
        #     "                   $(\"#large_img\").html(\"<img src=\\\"\"+ src_img +\"\\\" />\").css(\"display\", \"block\").css(\"z-index\", \"3\");\n"
        #     "                   \n"
        #     "                   iwidth =$(\"#large_img img\").width();   \n"
        #     "                   iheight =$(\"#large_img img\").height();   \n\n"
        #     "                   if (iheight+22 > $(window).height())\n"
        #     "                      iheight = $(window).height()-22;\n"
        #     "                   if (iwidth+22 > $(window).width())\n"
        #     "                   {\n"
        #     "                      iwidth = $(window).width()-22;\n"
        #     "                    }\n"
        #     "                   $(\"#large_img\").height(iheight).width(iwidth).css(\"overflow\",\"auto\");\n"
        #     "                });\n"
        #     "                \n"
        #     "                $(document).on(\"click\",\"#large_img img\",function(){\n"
        #     "                   $(\"#large_img\").html(\"\").css(\"display\", \"hidden\").css(\"z-index\", \"-3\");\n"
        #     "                });\n"
        #     "                if ($(\".page_middle\").height() < 600 && flag ===0 ) $(\".page_middle\").height(600);\n\n\n"
        #     "                \n"
        #     "                $(\".main_left .block3\").click(function(){  \n"
        #     "                              location.href = \"http://www.meteo.nw.ru/articles/index.php?id=674\";\n"
        #     "                              });\n"
        #     "                $(\"#corrup-link\").click(function(){  \n"
        #     "                              location.href = \"http://www.meteo.nw.ru/articles/index.php?id=1012\";\n"
        #     "                              });\n"
        #     "                $(\".f1\").click(function(){  \n"
        #     "                              window.open(\"http://www.kareliameteo.ru\", \"_blank\");\n"
        #     "                              });\n"
        #     "                $(\".f2\").click(function(){\n"
        #     "/*                              window.open(\"http://www.pogoda-pskov.ru\", \"_blank\");*/\n"
        #     "                              window.open(\"http://psk.meteo.nw.ru\", \"_blank\");\n"
        #     "                              });\n"
        #     "                $(\".f3\").click(function(){\n"
        #     "                              window.open(\"http://www.pogodavn.ru\", \"_blank\");\n"
        #     "                              });\n"
        #     "                $(\".f4\").click(function(){\n"
        #     "                              window.open(\"http://meteo39.ru\", \"_blank\");\n"
        #     "                              });\n"
        #     "                $(\"#library-link\").click(function(){\n"
        #     "                              //window.open(\"https://www.prlib.ru/search?key=%D1%81%D0%B7%20%D1%83%D0%B3%D0%BC%D1%81&page=3\", \"_blank\");\n"
        #     "                              window.open(\"http://www.meteo.nw.ru/articles/index.php?id=1025\", \"_blank\");\n"
        #     "                });                              \n"
        #     "                $(\"#logo\").click(function(){\n"
        #     "                              location.href = \"/\";\n"
        #     "                              });\n"
        #     "                $(\".lmenu .m1\").click(function(){\n"
        #     "                                                     $(this).toggleClass(\"active\").next(\".group\").slideToggle(\"fast\");\n"
        #     "                                                     /*$(this).toggleClass(\"active\");*/\n"
        #     "                                                     /*$(this).find(\"div\").slideToggle(\"fast\");*/\n"
        #     "                                                    /* $(this).find(\"div\").toggleClass(\"active\");*/\n"
        #     "                                         });\n\n"
        #     "                              \n"
        #     "     });\n"
        #     "     </script>\n"
        #     "      <div id=\"d_overlay\" onclick=\"iframe_overlay_off()\">\n"
        #     "          <div id=\"d_overlay_div\">\n"
        #     "              \n"
        #     "          </div>\n"
        #     "      </div>\n"
        #     "      <div id=\"large_img\" style=\"display: hidden\"></div>\n"
        #     "      <div class=\"wrap whead\">\n"
        #     "          <div class=\"head\">\n"
        #     "              <div class=\"hline\">\n"
        #     "                 <div id=\"home\" title=\"на главнуі\" class=\"float\"><a href=\"/\"><img src=\"/images/css/home.jpg\" /></a></div>\n"
        #     "                 <div id=\"map\" title=\"карта сайта\" class=\"float\"><a href=\"/util/site_treed.php?mid=207\"><img src=\"/images/css/map.jpg\" /></a></div>\n"
        #     "                 <div id=\"mail\" title=\"написать письмо\" class=\"float\"><a href=\"mailto:info@meteo.nw.ru\"><img src=\"/images/css/mail.jpg\" /></a></div>\n"
        #     "                 <div id=\"login\" class=\"float\"><a href='/util/login_form.php'><img align='absmiddle' src='/images/enter_d.jpg'/>Вход</a></div>\n"
        #     "                 <div id=\"map\" title=\"поиск по сайту\" class=\"float\" ><a href=\"/search.php\"><img src=\"/images/css/search.jpg\" /></a></div>\n"
        #     "                 <div id=\"date\" class=\"float\">\n"
        #     "    08 октября 2020, четверг\n"
        #     "             </div>\n"
        #     "             <div class=\"clear\"></div>\n"
        #     "          </div>\n"
        #     "          <div class=\"hlogo\">\n"
        #     "              <div id=\"logo\" class=\"float\">\n"
        #     "              </div>\n"
        #     "              <div id=\"name\" class=\"float\">\n"
        #     "              ФГБУ «Северо-Западное управление<br />\n"
        #     "              по гидрометеорологии<br /> и мониторингу<br />\n"
        #     "              окружающей среды»<br />\n"
        #     "              </div>\n"
        #     "              <div id=\"rhead\" class=\"float\"><div id=\"cur\" >&nbsp;</div>\n"
        #     "                  <div id=\"jam\">&nbsp;</div>\n"
        #     "                  <div id=\"filials\">\n"
        #     "                  ФИЛИАЛЫ:<br />\n"
        #     "                      <div class=\"f1 fil float\" title=\"сайт Карельского ЦГМС\"></div>\n"
        #     "                      <div class=\"f2 fil float\" title=\"сайт Псковского ЦГМС\"></div>\n"
        #     "                      <div class=\"f3 fil float\" title=\"сайт Новгородского ЦГМС\"></div>\n"
        #     "                      <div class=\"f4 fil last float\" title=\"сайт Калининградского ЦГМС\"></div>\n"
        #     "                      <div class=\"clear\"></div>\n"
        #     "                  </div>\n"
        #     "              </div>\n"
        #     "              <div class=\"clear\"></div>\n"
        #     "          </div><div class=\"hmenu1\">\n"
        #     "              <div class=\"hmenu2\">\n"
        #     "                    <div class=\"hmenu3\"><div title=\"\" class=\"float hmenuun \"><a href=\"/\">главная</a></div><div class=\"float hmenudiv\"></div><div title=\"новости\" class=\"float hmenuun \"><a href=\"/news/news_paged.php\">новости</a></div><div class=\"float hmenudiv\"></div><div title=\"Климат Санкт-Петербурга и Ленинградской области\" class=\"float hmenuun \"><a href=\"/articles/index.php?id=2\">климат</a></div><div class=\"float hmenudiv\"></div><div title=\"мониторинг загрязнения окружающей среды\" class=\"supersmall float hmenuun \"><a href=\"/articles/index.php?id=552\"> мониторинг загрязнения<br />окружающей среды</a></div><div class=\"float hmenudiv\"></div><div title=\"погода сейчас\" class=\"float hmenuun active\"><a href=\"/weather/lo_meteod.php\">погода сейчас</a></div><div class=\"float hmenudiv\"></div><div title=\"прогноз погоды\" class=\"float hmenuun \"><a href=\"/forecs/foreclo3daysd.php\">прогноз погоды</a></div><div class=\"float hmenudiv\"></div><div title=\"статьи\" class=\"float hmenuun \"><a href=\"/articles/index.php?id=1225\">статьи</a></div><div class=\"float hmenudiv\"></div><div title=\"ФГБУ «Северо-Западное УГМС»\" class=\"float hmenuun \"><a href=\"/articles/index.php?id=6\">о нас</a></div><div class=\"float hmenudiv\"></div><div title=\"гостевая книга\" class=\"float hmenuun \"><a href=\"/util/guestbookd.php\">гостевая книга</a></div><div class=\"float hmenudiv\"></div><div title=\"Метеоявления и прогноз осадков по ДМРЛ\" class=\"float hmenuun \"><a href=\"/util/raind.php\">Дождевик</a></div><div class=\"clear\"></div>\n"
        #     "                    </div>\n"
        #     "              </div>\n"
        #     "          </div></div>\n"
        #     "  </div>\n"
        #     "  <div class=\"wrap wbody1_main_a\">\n"
        #     "      <div class=\"wrap wbody2_main_a\">\n"
        #     "          <div class=\"body\"><div class=\"main_content\">\n"
        #     "                 <div class=\"page_left float\"><div class=\"mweather\"><div id=\"wbanner_page\" class=\"float\">\n"
        #     "                     <div id=\"wbtitle\">СЕЙЧАС В ПЕТЕРБУРГЕ</div>\n"
        #     "                     <div id=\"wbinfo\">\n"
        #     "                         <div class=\"wb1\">\n"
        #     "                             <div id=\"wpic\" class=\"float\"><img width=\"51\" title=\"Облачно\" src=\"/images/weather/real_weather/d3.png\" /></div>\n"
        #     "                             <div id=\"wtemp\" class=\"pos float\">+13.6 °C</div>\n"
        #     "                             <div class=\"clear\"></div>\n"
        #     "                         </div>\n"
        #     "                         <div class=\"wb2\">\n"
        #     "                             <div class=\"wtbl\">\n"
        #     "                                <div class=\"wttd\">Ветер: <span>южный</span></div>\n"
        #     "                                <div class=\"wttd\">Скорость ветра: <span>2-4 м/с</span></div>\n"
        #     "                                <div class=\"wttd\">Давление: <span>762.6 мм рт.ст.</span></div>\n"
        #     "                                <div class=\"wttd\">Влажность: <span>89%</span></div>\n"
        #     "                             </div>\n"
        #     "                         </div>\n"
        #     "                     </div>\n"
        #     "                     <div id=\"wbpostscr\">по данным м/с Санкт-Петербург за 08.10.2020 22 МСК</div>\n"
        #     "                 </div>\n"
        #     "                 <div class=\"clear\"></div>\n"
        #     "              </div><div class=\"lmenu\"><div class=\"m1\">Метеорологическая информация</div><div class=\"group\"><div class=\"m2\"><a href=\"/weather/lo_meteod.php\" title=\"Карта фактической погоды по Северо-Западному региону\">Карта фактической погоды по Северо-Западному региону</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=512\" title=\"Синоптическая карта погоды\">Синоптическая карта погоды</a></div></div><div class=\"m1 active\">Гидрологическая информация</div><div class=\"group active\"><div class=\"m2\"><span class=\"activem\" title=\"Карта фактического уровня воды в Финском заливе и реке Неве\">Карта фактического уровня воды</span></div></div><div class=\"m1\">Снимки со спутников NOAA</div><div class=\"group\"><div class=\"m2\"><a href=\"/articles/index.php?id=447\" title=\"Полный спутниковый снимок NOAA ИК-диапазон\">Полный снимок NOAA ИК-диапазон</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=448\" title=\"Фрагмент спутникового снимка NOAA (Чудское, Псковское озеро, озеро Ильмень)\">Фрагмент (Чудское, Псковское озеро, озеро Ильмень)</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=449\" title=\"Фрагмент спутникового снимка NOAA (Ладожское, Онежское озеро, озеро Белое)\">Фрагмент (Ладожское, Онежское озеро, озеро Белое)</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=450\" title=\"Фрагмент спутникового снимка NOAA (Финский залив)\">Фрагмент (Финский залив)</a></div></div><div class=\"m1\">Снимки с геостационарного спутника Meteosat-8</div><div class=\"group\"><div class=\"m2\"><a href=\"/articles/index.php?id=459\" title=\"Снимок с геостационарного спутника Meteosat-8 в видимом диапазоне\">Снимок в видимом диапазоне</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=656\" title=\"Анимированный снимок с геостационарного спутника Meteosat-8 в видимом диапазоне за 4 суток\">Анимированный снимок в видимом диапазоне</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=460\" title=\"Снимок с геостационарного спутника Meteosat-8 в ИК-диапазоне\">Снимок в ИК-диапазоне</a></div><div class=\"m2\"><a href=\"/articles/index.php?id=655\" title=\"Анимированный снимок с геостационарного спутника Meteosat-8 в ИК-диапазоне за сутки\">Анимированный снимок в ИК-диапазоне</a></div></div></div>\n"
        #     "                 </div>\n"
        #     "                 <div class=\"page_middle float\"><div class=\"nav_link\"><a href=\"/weather/lo_meteod.php\">погода сейчас</a>»&nbsp;&nbsp;&nbsp;Гидрологическая информация&nbsp;&nbsp;&nbsp;»&nbsp;&nbsp;&nbsp;Карта фактического уровня воды</div><h2 class=\"ttitle\">Карта фактического уровня воды в Финском заливе и реке Неве</h2><div class='zag3'>Фактический уровень воды за 8.10.2020 21 МСК, см</div>\n"
        #     "        <script src=\"/maps_util/markerwithlabel.js\" type=\"text/javascript\"></script>\n"
        #     "        <!--<script src=\"/maps_util/labeled_marker.js\" type=\"text/javascript\"></script>\n"
        #     "        <script src=\"/maps_util/marker_manager3.js\" type=\"text/javascript\"></script> -->\n"
        #     "        <style type=\"text/css\">\n"
        #     "          div.markerLabel, div.markerRed, div.markerGreen, div.markerBlack\n"
        #     "          {\n"
        #     "                  display: block;\n"
        #     "                  text-align: center;\n"
        #     "                  color: white;\n"
        #     "                  letter-spacing: 0px;\n"
        #     "                  font-size: 13px;\n"
        #     "                  font-family: Arial;\n"
        #     "                  font-style: bold;\n"
        #     "                  z-index: 3;\n"
        #     "                  text-align: center;\n"
        #     "          }\n"
        #     "          div.markerRed\n"
        #     "          {\n"
        #     "                  color: red;\n"
        #     "          }\n"
        #     "          div.markerGreen\n"
        #     "          {\n"
        #     "                  color: green;\n"
        #     "          }\n"
        #     "          div.markerBlack\n"
        #     "          {\n"
        #     "                  color: black;\n"
        #     "          }\n"
        #     "        </style>\n"
        #     "     <script type=\"text/javascript\">\n\n"
        #     "       //createMarkerHandler(marker, pointData.click_event, pointData.click_handler, pointData.bubble);\n"
        #     "        function createMarkerHandler(marker, event, type, handler, text)\n"
        #     "        {\n"
        #     "                return function()\n"
        #     "                {\n"
        #     "                        switch(type)\n"
        #     "                        {\n"
        #     "                            case 'bubble':\n"
        #     "                               if (event == 'mout')\n"
        #     "                                  marker.closeInfoWindow();\n"
        #     "                               else\n"
        #     "                                  marker.openInfoWindowHtml(text);\n"
        #     "                               break;\n"
        #     "                            case 'new_page':\n"
        #     "                               window.open(handler);\n"
        #     "                               break;\n"
        #     "                        }\n"
        #     "                        return false;\n"
        #     "                };\n"
        #     "        }\n"
        #     "        function createMarkerMoverHandler(marker, text)\n"
        #     "        {\n"
        #     "                return function()\n"
        #     "                {\n"
        #     "                        marker.openInfoWindowHtml(text);\n"
        #     "                        return false;\n"
        #     "                };\n"
        #     "        }\n"
        #     "        function createMarkerClose(marker)\n"
        #     "        {\n"
        #     "                return function()\n"
        #     "                {\n"
        #     "                        marker.closeInfoWindow();\n"
        #     "                        return false;\n"
        #     "                };\n"
        #     "        }\n\n"
        #     "        function createMarker(map_n, pointData) {\n"
        #     "                var latlng = new google.maps.LatLng(pointData.latitude, pointData.longitude);\n"
        #     "                var labelClassM = (pointData.labelClass.length > 0) ? pointData.labelClass : 'lMarker'; \n"
        #     "                switch (pointData.icon_type)\n"
        #     "                {\n"
        #     "                  case 'big_red':\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(16,16), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://uwmike.com/maps/manhattan/img/red-marker.png',\n"
        #     "                          scaledSize   : new google.maps.Size(32, 32)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  case 'small_red':\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(6,6), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/marker3.png',\n"
        #     "                          scaledSize   : new google.maps.Size(12, 12)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  case 'red':\n"
        #     "                      var icon_width = (pointData.abbr.length*11 < 32) ? 24 : pointData.abbr.length*11;\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(15,7), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/red_plate_round.gif',\n"
        #     "                          scaledSize   : new google.maps.Size(icon_width, 16)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  case 'grey':\n"
        #     "                      var icon_width = (pointData.abbr.length*11 < 32) ? 24 : pointData.abbr.length*11;\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(15,7), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/grey_plate_round.gif',\n"
        #     "                          scaledSize   : new google.maps.Size(icon_width, 16)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  case 'blue':\n"
        #     "                      var icon_width = (pointData.abbr.length*11 < 32) ? 24 : pointData.abbr.length*11;\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(15,7), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/blue_plate_round.gif',\n"
        #     "                          scaledSize   : new google.maps.Size(icon_width, 16)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  case 'green':\n"
        #     "                      var icon_width = (pointData.abbr.length*11 < 32) ? 24 : pointData.abbr.length*11;\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(15,7), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/green_plate_round.gif',\n"
        #     "                          scaledSize   : new google.maps.Size(icon_width, 16)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  case 'pink':\n"
        #     "                      var icon_width = (pointData.abbr.length*11 < 32) ? 24 : pointData.abbr.length*11;\n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(15,7), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/pink_plate_round.gif',\n"
        #     "                          scaledSize   : new google.maps.Size(icon_width, 16)\n"
        #     "                          }; \n\n"
        #     "                      break;\n"
        #     "                  case 'lighblue':\n"
        #     "                      var icon_width = (pointData.abbr.length*11 < 32) ? 24 : pointData.abbr.length*11;\n"
        #     "                       var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(15,7), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://www.meteo.nw.ru/images/maps/lighblue_plate_round.gif',\n"
        #     "                          scaledSize   : new google.maps.Size(icon_width, 16)\n"
        #     "                          }; \n"
        #     "                      break;\n"
        #     "                  default:\n"
        #     "                  \n"
        #     "                      var iconImage = {\n"
        #     "                          anchor : new google.maps.Point(16, 32), \n"
        #     "                          origin : new google.maps.Point(0,0),\n"
        #     "                          url    : 'http://maps.google.com/mapfiles/ms/icons/red-dot.png',\n"
        #     "                          scaledSize   : new google.maps.Size(32, 32)\n"
        #     "                          }; \n"
        #     "                      break;\n\n"
        #     "                }\n"
        #     "                temp_click = (pointData.click_event == '') ? false : true;\n"
        #     "                temp_over = (pointData.over_event == '') ? false : true;\n"
        #     "                \n"
        #     "                var marker = new MarkerWithLabel({\n"
        #     "                    position: latlng,\n"
        #     "                    draggable: false,\n"
        #     "                    raiseOnDrag: false,\n"
        #     "                    map: map_n,\n"
        #     "                    labelContent: pointData.abbr,\n"
        #     "                    labelAnchor: new google.maps.Point(8, 7),\n"
        #     "                    labelClass: labelClassM, // the CSS class for the label\n"
        #     "                    labelStyle: {opacity: 0.75},\n"
        #     "                    icon: {\n"
        #     "                       url:iconImage.url,\n"
        #     "                       origin:iconImage.origin,\n"
        #     "                       anchor:iconImage.anchor,\n"
        #     "                       scaledSize:iconImage.scaledSize\n"
        #     "                    }\n"
        #     "                });\n"
        #     "                var infowindow = new google.maps.InfoWindow({\n"
        #     "                    content: pointData.bubble\n"
        #     "                });\n\n"
        #     "                \n"
        #     "                if (temp_over)\n"
        #     "                {\n"
        #     "                   switch (pointData.over_event)\n"
        #     "                   {\n"
        #     "                       case 'bubble':\n"
        #     "                       default:\n"
        #     "                         google.maps.event.addListener(marker, 'mouseover', function () {infowindow.open(map_n,marker); });\n"
        #     "                         google.maps.event.addListener(marker, 'mouseout', function () {infowindow.close(); });\n"
        #     "                  }\n"
        #     "                }\n"
        #     "                if (temp_click)\n"
        #     "                {\n"
        #     "                   switch (pointData.click_event)\n"
        #     "                   {\n"
        #     "                       case 'new_page':\n"
        #     "                               google.maps.event.addListener(marker, 'click', function () {window.open(pointData.click_handler);});\n"
        #     "                               break;\n"
        #     "                       case 'bubble':\n"
        #     "                       default:\n"
        #     "                          google.maps.event.addListener(marker, 'click', function () {infowindow.open(map_n,marker); });\n"
        #     "                  }\n"
        #     "                }\n\n"
        #     "                \n"
        #     "                /*\n"
        #     "                switch (pointData.eventMethod)\n"
        #     "                {\n"
        #     "                  case 'click':\n"
        #     "                     var click_handler = createMarkerClickHandler(marker, pointData.bubble);\n"
        #     "                     google.maps.event.addListener(marker, 'click', click_handler);\n"
        #     "                     break;\n"
        #     "                  case 'mouseover':\n"
        #     "                     var mover_handler = createMarkerMoverHandler(marker, pointData.bubble);\n"
        #     "                     var close_infwindow = createMarkerClose(marker);\n"
        #     "                     google.maps.event.addListener(marker, 'mouseover', mover_handler);\n"
        #     "                     google.maps.event.addListener(marker, 'mouseout',  close_infwindow);\n"
        #     "                     break;\n"
        #     "                  default:\n"
        #     "                     break;\n"
        #     "                }\n"
        #     "                */\n\n"
        #     "             /*\n"
        #     "                var listItem = document.createElement('li');\n"
        #     "                listItem.innerHTML = '<div class=\"label\">'+pointData.abbr+'</div><a href=\"' + pointData.wp + '\">' + pointData.name + '</a>';\n"
        #     "                listItem.getElementsByTagName('a')[0].onclick = click_handler;\n"
        #     "                listItem.getElementsByTagName('a')[0].mouseover = mover_handler;\n"
        #     "                //document.getElementById('sidebar-list').appendChild(listItem);\n"
        #     "              */\n"
        #     "                return marker;\n"
        #     "        }\n\n"
        #     "        function windowHeight() {\n"
        #     "                // Standard browsers (Mozilla, Safari, etc.)\n"
        #     "                if (self.innerHeight)\n"
        #     "                        return self.innerHeight;\n"
        #     "                // IE 6\n"
        #     "                if (document.documentElement && document.documentElement.clientHeight)\n"
        #     "                        return document.documentElement.clientHeight;\n"
        #     "                // IE 5\n"
        #     "                if (document.body)\n"
        #     "                        return document.body.clientHeight;\n"
        #     "                // Just in case.\n"
        #     "                return 0;\n"
        #     "        }\n\n"
        #     "        /*\n"
        #     "        function handleResize() {\n"
        #     "                var height = windowHeight() - document.getElementById('toolbar').offsetHeight - 30;\n"
        #     "                document.getElementById('map').style.height = height + 'px';\n"
        #     "                document.getElementById('sidebar').style.height = height + 'px';\n"
        #     "        }\n"
        #     "        */\n\n\n"
        #     "      // window.onresize = handleResize;\n"
        #     "        // window.onunload = GUnload;</script><div id=\"mapm\" style=\"width:539px; height:600px\"></div><script type=\"text/javascript\">var markers_mapm = [\n"
        #     "             {\n"
        #     "                'abbr': '-2',\n"
        #     "                'name': '',\n"
        #     "                'latitude':60.61,\n"
        #     "                'longitude':28.56,\n"
        #     "                'bubble':'<b>Высоцк-Угольный</b><br>уровень: <i>-2</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '-5',\n"
        #     "                'name': '',\n"
        #     "                'latitude':60.03,\n"
        #     "                'longitude':26.98,\n"
        #     "                'bubble':'<b>Гогланд 2</b><br>уровень: <i>-5</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '11',\n"
        #     "                'name': '',\n"
        #     "                'latitude':59.93,\n"
        #     "                'longitude':30.27,\n"
        #     "                'bubble':'<b>Горный институт</b><br>уровень: <i>11</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '-1',\n"
        #     "                'name': '',\n"
        #     "                'latitude':59.98,\n"
        #     "                'longitude':29.77,\n"
        #     "                'bubble':'<b>Кронштадтский футшток</b><br>уровень: <i>-1</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '5',\n"
        #     "                'name': '',\n"
        #     "                'latitude':59.91,\n"
        #     "                'longitude':30.25,\n"
        #     "                'bubble':'<b>Н. Порт</b><br>уровень: <i>5</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '65',\n"
        #     "                'name': '',\n"
        #     "                'latitude':59.86,\n"
        #     "                'longitude':30.49,\n"
        #     "                'bubble':'<b>Обуховский завод</b><br>уровень: <i>65</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '-7',\n"
        #     "                'name': '',\n"
        #     "                'latitude':60.71,\n"
        #     "                'longitude':28.73,\n"
        #     "                'bubble':'<b>Порт Выборг</b><br>уровень: <i>-7</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '-7',\n"
        #     "                'name': '',\n"
        #     "                'latitude':60.33,\n"
        #     "                'longitude':28.74,\n"
        #     "                'bubble':'<b>Приморск-2</b><br>уровень: <i>-7</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '447',\n"
        #     "                'name': '',\n"
        #     "                'latitude':59.96,\n"
        #     "                'longitude':31.04,\n"
        #     "                'bubble':'<b>г.Петрокрепость</b><br>уровень: <i>447</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             },\n"
        #     "             {\n"
        #     "                'abbr': '-9',\n"
        #     "                'name': '',\n"
        #     "                'latitude':59.97,\n"
        #     "                'longitude':29.10,\n"
        #     "                'bubble':'<b>п. Шепелево</b><br>уровень: <i>-9</i> см<br /><br /><br />',\n"
        #     "                'labelId': '',\n"
        #     "                'click_event' : '',\n"
        #     "                'over_event' : 'bubble',\n"
        #     "                'click_handler' : '',\n"
        #     "                'over_handler' : '',\n"
        #     "                'labelClass': '',\n"
        #     "                'icon_type': 'green'\n"
        #     "             }\n"
        #     "];\n"
        #     "                 function init_mapm() {\n"
        #     "                       //  handleResize();\n"
        #     "                         var mapOptions = {\n"
        #     "                              zoom: 7,\n"
        #     "                              center: new google.maps.LatLng(60.217991, 29)\n"
        #     "                         };\n\n"
        #     "                         map_mapm = new google.maps.Map(document.getElementById(\"mapm\"),mapOptions);\n"
        #     "                        // map_mapm.addControl(new GSmallMapControl());\n"
        #     "                        // map_mapm.setCenter(new GLatLng(60.217991, 29), 7);\n"
        #     "                        // map_mapm.addControl(new GMapTypeControl());\n"
        #     "                        // map_mapm.enableContinuousZoom();\n"
        #     "                         // изменение масштаба колесиком мыши\n"
        #     "                       //  map_mapm.enableScrollWheelZoom();\n"
        #     "                         drawMarkers_mapm();\n\n"
        #     "                 }\n"
        #     "                 $(document).ready(function(){\n"
        #     "                         init_mapm();});\n"
        #     "                 function drawMarkers_mapm()\n"
        #     "                 {\n"
        #     "                         for(id_mapm in markers_mapm) {\n"
        #     "                                 createMarker(map_mapm, markers_mapm[id_mapm]);\n"
        #     "                         }\n"
        #     "                         }</script></div>\n"
        #     "                 <div class=\"page_right float\"><div class=\"block1 block\">\n"
        #     "                          <div class=\"rtbl\">\n"
        #     "                      				<a href=\"/weather/lo_meteod.php\" title=\"Карта фактической погоды по Северо-Западному региону\"><img src=\"/images/map_temp.jpg\" /></a><br />\n"
        #     "                              <a href=\"/weather/lo_meteod.php\" title=\"Карта фактической погоды по Северо-Западному региону\">Карта фактической погоды</a>\n"
        #     "                          </div>\n"
        #     "                          <div class=\"rtbl\">\n"
        #     "                      				<a href=\"/articles/index.php?id=512\" title=\"Синоптическая карта погоды\"><img src=\"/images/map_meteo.jpg\" /></a><br />\n"
        #     "                              <a href=\"/articles/index.php?id=512\" title=\"Синоптическая карта погоды по Северо-Западному региону\">Синоптическая карта погоды</a>\n"
        #     "                          </div>\n"
        #     "                      	  <div class=\"list_link\"><span><a href=\"/weather/lo_meteod.php\">Все карты</a></span></div>\n"
        #     "                        </div>\n"
        #     "                        <div class=\"block_ad block\">\n"
        #     "                                <!-- -ндекс.-ирект -->\n"
        #     "                                <div id=\"yandex_ad\"></div>\n"
        #     "                                <script type=\"text/javascript\">\n"
        #     "                                (function(w, d, n, s, t) {\n"
        #     "                                w[n] = w[n] || [];\n"
        #     "                                w[n].push(function() {\n"
        #     "                                Ya.Direct.insertInto(76550, \"yandex_ad\", {\n"
        #     "                                site_charset: \"windows-1251\",\n"
        #     "                                ad_format: \"direct\",\n"
        #     "                                font_size: 0.9,\n"
        #     "                                type: \"vertical\",\n"
        #     "                                limit: 3,\n"
        #     "                                title_font_size: 1,\n"
        #     "                                site_bg_color: \"FFFFFF\",\n"
        #     "                                bg_color: \"DBE2ED\",\n"
        #     "                                title_color: \"0000CC\",\n"
        #     "                                url_color: \"006600\",\n"
        #     "                                text_color: \"000000\",\n"
        #     "                                hover_color: \"0066FF\",\n"
        #     "                                favicon: true\n"
        #     "                                });\n"
        #     "                                });\n"
        #     "                                t = d.documentElement.firstChild;\n"
        #     "                                s = d.createElement(\"script\");\n"
        #     "                                s.type = \"text/javascript\";\n"
        #     "                                s.src = \"http://an.yandex.ru/system/context.js\";\n"
        #     "                                s.setAttribute(\"async\", \"true\");\n"
        #     "                                t.insertBefore(s, t.firstChild);\n"
        #     "                                })(window, document, \"yandex_context_callbacks\");\n"
        #     "                                </script>\n"
        #     "                       </div>\n"
        #     "                        <div class=\"block3 block\"></div>\n"
        #     "                        <div class=\"block4 block\"></div></div>\n"
        #     "                 <div class=\"clear\"></div>\n"
        #     "              </div>\n"
        #     "          </div>\n"
        #     "      </div>\n"
        #     "  </div>\n"
        #     "  <div class=\"wrap wbottom\">\n"
        #     "      <div class=\"bottom\">\n"
        #     "          <div class=\"bottom1 float\">Copyright (c) 2007-2020 ФГБУ<br /> Северо-Западное УГМС.<br /> Все права защищены.</div>\n"
        #     "          <div class=\"bottom2 float\">При использовании всех размещенных на сайте материалов ссылка обязательна. Представленная \n"
        #     "                                     информация предназначена исключительно для личного пользования и не может использоваться в \n"
        #     "                                     коммерческих целях, для планирования мероприятий, реализация которых связана с риском \n"
        #     "                                     материальнvх потерь или человеческих жертв. Для получения официальных данных обращайтесь в \n"
        #     "                                     группу бухгалтерии по работе с заказчиками.</div>\n"
        #     "          <div class=\"bottom3 float\">\n"
        #     "          <!--Rating@Mail.ru COUNTER--><script language=\"JavaScript\" type=\"text/javascript\"><!--\n"
        #     "  d=document;var a='';a+=';r='+escape(d.referrer)\n"
        #     "  js=10//--></script><script language=\"JavaScript1.1\" type=\"text/javascript\"><!--\n"
        #     "  a+=';j='+navigator.javaEnabled()\n"
        #     "  js=11//--></script><script language=\"JavaScript1.2\" type=\"text/javascript\"><!--\n"
        #     "  s=screen;a+=';s='+s.width+'*'+s.height\n"
        #     "  a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth)\n"
        #     "  js=12//--></script><script language=\"JavaScript1.3\" type=\"text/javascript\"><!--\n"
        #     "  js=13//--></script><script language=\"JavaScript\" type=\"text/javascript\"><!--\n"
        #     "  d.write('<a href=\"http://top.mail.ru/jump?from=1499589\"'+\n"
        #     "  ' target=\"_top\"><img src=\"http://d1.ce.b6.a1.top.mail.ru/counter'+\n"
        #     "  '?id=1499589;t=131;js='+js+a+';rand='+Math.random()+\n"
        #     "  '\" alt=\"іейтинг@Mail.ru\"'+' border=\"0\" height=\"40\" width=\"88\"/><\\/a>')\n"
        #     "  if(11<js)d.write('<'+'!-- ')//--></script><noscript><a\n"
        #     "  target=\"_top\" href=\"http://top.mail.ru/jump?from=1499589\"><img\n"
        #     "  src=\"http://d1.ce.b6.a1.top.mail.ru/counter?js=na;id=1499589;t=131\"\n"
        #     "  border=\"0\" height=\"40\" width=\"88\"\n"
        #     "  alt=\"іейтинг@Mail.ru\"/></a></noscript><script language=\"JavaScript\" type=\"text/javascript\"><!--\n"
        #     "  if(11<js)d.write('--'+'>')//--></script><!--/COUNTER-->\n"
        #     "     \n"
        #     "          <!-- begin of Top100 logo -->\n"
        #     "<!--  <a href=\"http://top100.rambler.ru/top100/\"><img src=\"http://top100-images.rambler.ru/top100/banner-88x31-rambler-gray2.gif\" alt=\"Rambler's Top100\" width=\"88\" height=\"31\" border=\"0\" /></a>   -->\n"
        #     "  <!-- end of Top100 logo -->\n\n"
        #     "  <!--LiveInternet counter--><script type=\"text/javascript\"><!--\n"
        #     "  document.write(\"<a href='http://www.liveinternet.ru/click' \"+\n"
        #     "  \"target=_blank><img src='http://counter.yadro.ru/hit?t13.5;r\"+\n"
        #     "  escape(document.referrer)+((typeof(screen)==\"undefined\")?\"\":\n"
        #     "  \";s\"+screen.width+\"*\"+screen.height+\"*\"+(screen.colorDepth?\n"
        #     "  screen.colorDepth:screen.pixelDepth))+\";u\"+escape(document.URL)+\n"
        #     "  \";\"+Math.random()+\n"
        #     "  \"' alt='' title='LiveInternet: показано число просмотров за 24\"+\n"
        #     "  \" часа, посетителей за 24 часа и за сегодня' \"+\n"
        #     "  \"border=0 width=88 height=31><\\/a>\")//--></script><!--/LiveInternet--></div>\n"
        #     "          <div class=\"clear\"></div>\n"
        #     "      </div>\n"
        #     "  </div>\n"
        #     "  <script type=\"text/javascript\">\n"
        #     "                  function iframe_overlay_on() {\n"
        #     "                      document.getElementById(\"d_overlay\").style.display = \"block\";\n"
        #     "                      set_iframe();\n"
        #     "                      \n"
        #     "                  }\n"
        #     "                  \n"
        #     "                  function iframe_overlay_off() {\n"
        #     "                      document.getElementById(\"d_overlay\").style.display = \"none\";\n"
        #     "                  }\n"
        #     "                  function set_iframe(){\n"
        #     "                            $(\"#d_overlay_div\").html(\"<iframe width=100% height=100% src='https://www.prlib.ru/search?key=%D1%81%D0%B7%20%D1%83%D0%B3%D0%BC%D1%81&page=3'></iframe>\");                  \n"
        #     "                  }\n"
        #     "  </script>\n"
        #     " \n"
        #     "    <!-- jQuery first, then Popper.js, then Bootstrap JS -->\n"
        #     "    <script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\n"
        #     "    <script type=\"text/javascript\" src=\"/jscripts/jquery-ui-1.10.0.custom.js\"></script>\n"
        #     "    <script type=\"text/javascript\" src=\"/jscripts/jquery.tinycarousel.min.js\"></script>\n\n"
        #     "       </body></html>")

        regex = r"markers_mapm = \[([^\[]+)\]"

        test_str = (_get_html())

        matches = re.finditer(regex, test_str, re.MULTILINE)

        for matchNum, match in enumerate(matches, start=1):

            print("Match {matchNum} was found at {start}-{end}: {match}".format(matchNum=matchNum, start=match.start(),
                                                                                end=match.end(), match=match.group()))

            for groupNum in range(0, len(match.groups())):
                groupNum = groupNum + 1

                print("Group {groupNum} found at {start}-{end}: {group}".format(groupNum=groupNum,
                                                                                start=match.start(groupNum),
                                                                                end=match.end(groupNum),
                                                                                group=match.group(groupNum)))
