#!/bin/bash 
echo ''
echo ''
echo 'pppp    pppp    RRRR'
echo 'p   p   p   p   R   R'
echo 'p   p   p   p   R   R'
echo 'pppp    pppp    RRRR'
echo 'p       p       R   R'
echo 'p       p       R   R'
echo 'p       p       R   R'
echo ''
echo ''

echo  'Submit keys'
scp ~/Projects/Universe/keys_pr.py belovgm19@91.224.22.111:~/proj/uni/keys.py
ssh -tt belovgm19@91.224.22.111 << EOF
cd ~/proj/uni/
git fetch --all
git reset --hard origin/master
echo 'Git Pull -- Ok'
sh cmd/uwr
logout
EOF

