#!/bin/bash 
echo 'Submit keys...'
scp ~/PycharmProjects/Universe/keys_ts.py belovgm19@91.224.22.111:~/proj/uni_test/keys.py
echo 'Ok'
echo 'Git Pull...'
ssh -tt belovgm19@91.224.22.111 << EOF
echo 'Git Pull...'
source ~/py37/bin/activate
cd ~/proj/uni_test/
git pull
echo 'Git Pull -- Ok'
logout
EOF